### ISSUE TITLE
Keep asking for sign in forever

### ISSUE THREAD

**Issue by assincrono** [Keviinplz/mbtify#13]
Whenever I try to sign in with my spotify account, it says "log in with a different account" or "sign in with spotify" forever.

**Comment by Keviinplz** [comment]
Hi @nandowastaken,

Thanks for your interest in the project :), currently I'm using a dev account of the Spotify OAuth2 service, because of that I have to allow users by hand (with their emails) in order to be able to connect their spotify accounts with the app.

I hope soon the app will be production ready to change to prod account, but if you want to help me with the development, feel free to share with me your email (has to be an email linked to a spotify account) to allow you in the app :)!
